project:
  name: ""
  mode: "dev"
  port: 8181
  start_time: "2020-07-01"
  matchine_id: 1
log:
  level: "debug"
  filename: ""
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "39.101.77.206"
  port: 3306
  user: "itoffice"
  password: "Wksycxy0.0"
  dbname: "recruit"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: "39.101.77.206"
  port: 6379
  db: 0
  password: "Wksycxy0.0"
  pool_size: 100
